### ISSUE TITLE
Exemplo de uso

### ISSUE THREAD

**Issue by lpanebr** [lpanebr/xml-listify#1]
Incluir documentação com exemplo de uso no readme.

**Comment by lpanebr** [comment]
@laysgarcia num sei se vc já usou ou apenas a @layane-vieira

Já nem lembro com fazem pra usar.. :-/

Por favor me informe qual comando etc usam pra rodar isto?

**Comment by layane-vieira** [comment]
Chave: 

cdwin - Entrar na pasta
lgp-listify 
lgp-listify -filename [nome do arquivo] 

Observações: 
O arquivo chave-ok é o arquivo que já foi enviado e que deu certo
O arquivo chave é o arquivo com problema 

[chave-ok.txt](https://github.com/lpanebr/xml-listify/files/911018/chave-ok.txt)

[chave.txt](https://github.com/lpanebr/xml-listify/files/911023/chave.txt)

**Comment by lpanebr** [comment]
Descobri a causa do problema no arquivo. Vejam na linha 4 abaixo como a indentação é interrompida e parece até falta o número:
![image](https://cloud.githubusercontent.com/assets/129185/24876813/7bf58112-1e03-11e7-84bc-d4d9eae83507.png)

@layane-vieira pode por favor checar no DOC se houve algum problema?

**Comment by lpanebr** [comment]
# Comandos
Depois que você já tiver preparado o arquivo `chave.txt`, basta:
 1. `cdwin` comando para entrar na pasta xml do artigo.
 2. `lgp-listify -filename chave.txt`

Se a saída for parecida com o exemplo abaixo deve estar udo OK. Siga adiante para o passo 3.
```xml
<list list-type="simple">
  <list-item><p>1. texto .... texto.</p></list-item>
  <list-item>
    <list list-type="simple">
      <list-item>	<p>2. texto .... texto.</p></list-item>
      <list-item>
        <list list-type="simple">
          <list-item>		<p>3. texto .... texto.</p></list-item>
          <list-item>		<p>3'. texto .... texto.</p></list-item>
          <list-item>
            <list list-type="simple">
              <list-item>			<p>4. texto .... texto.</p></list-item>
              <list-item>			<p>4\'. texto .... texto.</p></list-item>
            </list>
          </list-item>
        </list>
      </list-item>
      <list-item>	<p>2\'. texto .... texto.</p></list-item>
      <list-item>
        <list list-type="simple">
          <list-item>		<p>5. texto .... texto.</p></list-item>
          <list-item>		<p>5\'. texto .... texto.</p></list-item>
        </list>
      </list-item>
    </list>
  </list-item>
  <list-item><p>1'. texto .... texto.</p></list-item>
  <list-item>
``` 
Finalize com o comando a seguir que criará o arquivo `chave.xml` com o conteúdo do comando anterior.
3. `lgp-listify -filename chave.txt > chave.xml` 
4. Substitua esse conteúdo no arquivo XML original do artigo.

# Preparação do arquivo `chave.txt`
## Arquivo DOC
No DOC a indentação deve estar:
 - usando TABS (→)
 - uma linha por parágrafo (¶)
 - cada linha com estilo `Paragraph` aplicado
```
[Paragraph]   |   1. texto .... texto.¶
[Paragraph]   |   →2. texto .... texto.¶
[Paragraph]   |   →→3. texto .... texto.¶
[Paragraph]   |   →→3'. texto .... texto.¶
[Paragraph]   |   →→→4. texto .... texto.¶
[Paragraph]   |   →→→4’. texto .... texto.¶
[Paragraph]   |   →2’. texto .... texto.¶
[Paragraph]   |   →→5. texto .... texto.¶
[Paragraph]   |   →→5’. texto .... texto.¶
[Paragraph]   |   1'. texto .... texto.¶
[Paragraph]   |   →6. texto .... texto.¶
[Paragraph]   |   →6'. texto .... texto.¶
[Paragraph]   |   →→7. texto .... texto.¶
[Paragraph]   |   →→→8. texto .... texto.¶
[Paragraph]   |   →→→8'. texto .... texto.¶
[Paragraph]   |   →→7’. texto .... texto.¶
[Paragraph]   |   →→→9. texto .... texto.¶
[Paragraph]   |   →→→9'. texto .... texto.¶
```

## Arquivo XML
Depois de exportar o XML deve estar com a mesma estrutura do DOC. Observar pois as vezes as linhas podem se quebrar e gerar erro. 

```xml
<p>1. texto .... texto.</p>
<p>	2. texto .... texto.</p>
<p>		3. texto .... texto.</p>
<p>		3'. texto .... texto.</p>
<p>			4. texto .... texto.</p>
<p>			4’. texto .... texto.</p>
<p>	2’. texto .... texto.</p>
<p>		5. texto .... texto.</p>
<p>		5’. texto .... texto.</p>
<p>1'. texto .... texto.</p>
<p>	6. texto .... texto.</p>
<p>	6'. texto .... texto.</p>
<p>		7. texto .... texto.</p>
<p>			8. texto .... texto.</p>
<p>			8'. texto .... texto.</p>
<p>		7’. texto .... texto.</p>
<p>			9. texto .... texto.</p>
<p>			9'. texto .... texto.</p>
```

## Arquivo `chave.txt`
Apenas as linhas do arquivo XML que contém os itens da chave devem ser copiados para um novo arquivo chamado `chave`.

**Comment by lpanebr** [comment]
@layane-vieira veja aqui se a info acima está ok?

**Comment by layane-vieira** [comment]
@lpanebr As informações estão corretas. 
Falta inserir o processo final obtido através do comando: 

```xml
lgp-listify -filename [nome do arquivo] > [nome do NOVO arquivo]
```

**Comment by lpanebr** [comment]
@layane-vieira falta não.. É o passo 3. Optei por usar o nome chave.txt para deixar um comando que já pode ser copiado.
